development:
  adapter: postgresql
  encoding: unicode
  database: task
  host: localhost
  pool: 5
  username: task
  password: task

test:
  adapter: postgresql
  encoding: unicode
  database: task
  host: localhost
  pool: 5
  username: task
  password: task
